### ISSUE TITLE
"Rewind Stop" does not work if film is in the gate

### ISSUE THREAD

**Issue by 10MDS** [jareff-g/ALT-Scann8#133] opened 2024-03-10 15:14 UTC
An extreme test, but I'm doing a lot of extreme and senseless tests...

If I press "Rewind" with the film in the Gate, the "Rewind Stop" command is not accepted.
ALT-Scann blocked and I had to turn off the machine but in the meantime I turned off Rasberry (shutdown is not enough, you really need to disconnect the power), the motor continued to pull causing noise, vibrations and the risk of damaging itself.

I did the same test with Fast-Forward button, always with the film in the Gate, obviously the motor assumed the same behavior, but the Stop button worked this time, so I think only "Stop Rewind" needs to be reviewed better.

Mariano

**Comment by jareff-g** [comment] 2024-03-19 08:32
In August 2022 I added protection to prevent using Rewind/FF when there is film loaded thought film gate, however the change done recently to have all motors in neutral by default broke that protection, allowing rewind/FF to happen with film loaded though film gate.
The issue is now fixed, it will be available in next release (fix has been done on Arduino code, so do not forget to upload it to the scanner).

**Comment by jareff-g** [comment] 2024-03-24 14:21
Confirmed as working

**Closed by jareff-g** 2024-03-24 14:21 UTC
